import type { Metadata } from "next";
import { Header } from "@/components/header";
import { Navigation } from "@/components/navigation";
import { GlobalStyles } from "@/theme/globals";
import Providers from "./styled-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  
      <body>
        <Providers>
          <GlobalStyles />
          {children}
        </Providers>
      </body>
    </html>
  )
}
